### ISSUE TITLE
Server - 哪天踢球中报名的队员没有出现在当天的比赛里

### ISSUE THREAD

**Issue by keeploading** [keeploading/wof#58]
1. 创建一个哪天踢球投票，让几个球员投票；
2. 然后创建一场比赛在球员投票的日期中；

投票那天的球员没有自动出现在报名列表中。

**Comment by wxbhlj** [comment]
测试了没问题啊，回来再试试

2015-02-13 18:00 GMT+08:00 Yiru notifications@github.com:

**Comment by wxbhlj** [comment]
无法重现，关闭先
